config/routes.rb
CraigsListAlert::Application.routes.draw do
  devise_for :users

  resources :users

  resources :items
  resources :criterias
  match '/c/bookmarklet' => 'criterias#create_via_script', :as => "create_user_bookmarklet"

  match 'bookmarklet/js' => 'bookmarklet#js'

  
   root :to => "criterias#index"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/bookmarklet.rb
class Bookmarklet < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/criteria.rb
class Criteria < ActiveRecord::Base

	has_many :user_criterias, :dependent => :destroy  # has many through relationship, must define within the models
	has_many :users, :through => :user_criterias
	has_many :items


  attr_accessible :url, :title

  
 
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :url, :item, :location, :price, :title, :criteria_id

  	belongs_to :criteria

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

	has_many :user_criterias, :dependent => :destroy
	has_many :criterias, :through => :user_criterias

  attr_accessible :email, :name
end

app/models/user_criteria.rb
class UserCriteria < ActiveRecord::Base

	belongs_to :user
	belongs_to :criteria

  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	before_filter :authenticate_user! #Before filters may halt the request cycle. A common before filter is one which requires that a user is logged in for an action to be run. 

end

app/controllers/bookmarklet_controller.rb
class BookmarkletController < ApplicationController
# run the bookmarklet.html.erb page here
 #layout 'application' #Application layout is applied to every page within the application.
#def index
    # index run first by convention
    #helper_method :current_user
    
 #   @url = params[:url] 
#    @page_title = params[:title]
    
    # find_or_create_by_url(@url)
  #  search = Search.find_by_url(@url) || Search.create!(:url => @url) 

    # current_user.user_searches.find_or_create_by_search_id({:search_id => search.id, :title => @page_title})
 #   user_search = current_user.user_searches.find_by_search_id(search.id)
 #   user_search ||= current_user.user_searches.create!({:search_id => search.id, :title => @page_title})

 # end

  def js
    render :file => "bookmarklet/js", :content_type => Mime::JS, :layout => false #Mime is the type of file
  end

end

app/controllers/criterias_controller.rb
class CriteriasController < ApplicationController

	def new
		@criteria = Criteria.new
	end


	def create 
		#@criteria = Criteria.find_or_create_by_url(parama[:url])
		@criteria = current_user.criterias.create(params[:criteria]) #create is a saved method

    respond_to do |format|
      format.html { redirect_to(:action => "index") }
    end

	end

	def index
		@criterias = current_user.criterias.all
	end

	def destroy
		@criteria = current_user.criterias.find(params[:id])
		@criteria.destroy
		redirect_to(:action => "index")
	end

  def create_via_script
		@criteria = current_user.criterias.create(params[:criteria]) #create is a saved method
    render :nothing => true, :status => :ok
  end




end

app/controllers/items_controller.rb
class ItemsController < ApplicationController #controller is front end focused
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }

      render
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarlet_helper.rb
module BookmarletHelper

end

app/helpers/craigs_list_helper.rb
module CraigsListHelper
end

app/helpers/craigs_list_scraper_helper.rb
module CraigsListScraperHelper
end

app/helpers/criteria_helper.rb
module CriteriaHelper

	def bookmarklet_link_url
		# "javascript:d=document;s=d.createElement('script');s.src='http://localhost:3000/bookmarklets?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(d.title);d.body.appendChild(s);".html_safe
		"javascript:d=document;s=d.createElement('script');s.src='http://localhost:3000/bookmarklet/js';d.body.appendChild(s);".html_safe
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarklet/form.html.erb
<html>
  <body>
    <script type="text/javascript" src="/javascripts/postcl.js"></script>
  </body>
</html>

<h1>Bookmark created!</h1>

<%= @url %>
<%= @page_title %>

<%= link_to("Save this search", bookmarklet_link_url) %>

app/views/bookmarklet/index.html.erb
<div><h1>Welcome to Craigslist Alerter</h1></div>
<div class="wrapper">
<div id="first" class="bookmark"><%= image_tag "favorite.png", :size => "50x50" %></div>
<div id="second"><h2> Drag this bookmarklet to your browser </h2></div>
</div>

<!--<%= link_to("Drag me to your broswer", bookmarklet_link_url) %>

app/views/bookmarklet/js.html.erb
if (!($ = window.jQuery)) { // typeof jQuery=='undefined' works too  
	script = document.createElement( 'script' );  
script.src = 'http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js';  
script.onload=createAndRenderPopout;  
document.body.appendChild(script);  
}  
else {  
	createAndRenderPopout();  
}  


// Create a divs, containing a form and a submit button. 
function createDivs() {
return $("body").append("<form id=\"myForm\" action=\"<%= create_user_bookmarklet_url %>\" method=\"post\" style=\"width:400px; height:100px; padding:20px; font-family: courier,monospace; border:5px solid; margin:auto; text-align:center; border-radius: 50px; opacity:1; position:fixed; top:100px; left:0; right:0; z-index: 1; background-color: #FFFF66\"> Save this search! <br></br> Title Your Search: <input type=\"text\" name=\"title\"><br></br><input type=\"hidden\" name=\"url\" value=\""+window.location.href+"\"><input type=\"submit\" value=\"Save\"><input type=\"hidden\" name=\"authenticity_token\" value=\"<%= form_authenticity_token %>\"></form>")
}

//AJAX post form
$("#myForm").submit(function() {

  var url = $(this).attr("action")
  var sendCraigslistItem = $("<script></script>")
  .attr("src", url + "?" + $(this).serialize())
  .attr("async", "true")
  .attr("id", "postToCLScraper");

  $("body").append(sendCraigslistItem)
  setTimeout("closePopOut()", 100);

	return false;
})

function closePopOut() {
	if($("#myForm").length != 0)  {
    $("#myForm").detach()
	}

  if ($("#postToCLScraper").length != 0)  {
    $("#postToCLScraper").detach()
  }
}

function createAndRenderPopout() {
  closePopOut()
  createDivs();
}

app/views/criterias/index.html.erb
<% if @criterias.present? %> 

<h1>Saved Searches</h1>

<table >
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Date Created</th>
    <th class="remove"></th>
  </tr>

  <% @criterias.each do |criteria| %>
  <tr>
    <td><%= criteria.title %></td>
    <td><%= criteria.url %></td>
    <td><%= criteria.created_at %></td>
    <td class="remove"><%= link_to 'Remove', criteria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<br />

<div class="new_search"> <%= link_to 'New Search', new_criteria_path %> <div>

<p><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></p>       

<%else%>

<div class="wrapper">
<div id="first" class="bookmark"><%= image_tag "pow.jpg", :size => "110x100" %></div>
<div id="second"><%= image_tag "ai3.JPG"%></div>
<%= link_to("Drag me to your broswer", bookmarklet_link_url) %>
<%end%>
<%#link_to holds image_tag which holds images that is linked to js%>

app/views/criterias/new.html.erb
<div><h1>New item</h1></div>


<%= form_for(@criteria) do |f| %>
  <% if @criteria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@criteria.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>


  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div><h1>Listing items</h1></div>

<div><table>
  <tr>
    <th>Item</th>
    <th>Location</th>
    <th>Price</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.item %></td>
    <td><%= item.location %></td>
    <td><%= item.price %></td>
    <td><%= item.url %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table></div>

<br />

<div><%= link_to 'New Item', new_item_path %></div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @item.item %>
</p>

<p>
  <b>Location:</b>
  <%= @item.location %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Email:</b>
  <%= @item.email %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>CraigsListAlert</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	
</head>
<body>

	<%= yield %>

</body> 
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>